# Generated by Django 2.2.9 on 2020-08-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_32',
        ),
        migrations.AddField(
            model_name='product',
            name='price_40',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=4),
            preserve_default=False,
        ),
    ]
