# Generated by Django 2.2.9 on 2020-08-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200818_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_40',
            new_name='price_42',
        ),
    ]
